### PR TITLE
Staging

### PR DESCRIPTION
**Pull request by swynn**

### CODE REVIEW

**Comment by hopkinsju** [comment]
It seems like we can let this one go and just take your staging pull request. Once we are happy we can merge everything into master. What do you think?

**Comment by swynn** [comment]
Justin,

 

Yes, please.  I didn’t realise I had opened two pull requests. #25 is the one I had intended to send.

 

Steve

**Comment by hopkinsju** [comment]
Not at all - just had a huge fire to put out yesterday.

**Comment by swynn** [comment]
Yikes. 

 

Hope that’s out; I got a couple more calls this morning about problems that have easy fixes, so I’ll send another pull request soon.

 

Steve

**Pull request closed without merging**
